#!/bin/sh
# postrm script for kea-common
#
# see: dh_installdeb(1)

set -e

case "$1" in
    purge)
        dpkg-statoverride --force --remove /var/log/kea
	dpkg-statoverride --force --remove /var/lib/kea

	deluser --system _kea >/dev/null || /bin/true
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
